openapi: 3.0.0
info:
  title: Gymate
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Contact Us
paths:
  /auth/sign-up:
    post:
      tags:
        - Auth
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: koushik
                email: koushik@gmail.com
                phoneNumber: '7980064332'
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: koushik
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/profile:
    get:
      tags:
        - Auth
      summary: Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /contactus:
    post:
      tags:
        - Contact Us
      summary: Contact Us
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                fullName: '{{$randomFullName}}'
                email: '{{$randomExampleEmail}}'
                phoneNumber: '{{$randomPhoneNumber}}'
                class: Fitness
                comment: '{{$randomLoremParagraph}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}